### ISSUE TITLE
Arduino Library

### ISSUE THREAD

**Issue by SardinasJL** [jrbenito/PIMA#2]
Hi JRBenito.

I write this note to ask you: ¿Do you have a similar library for Arduino languaje? I want connect a pima meter (model Nansen Lumen MD3) to Arduino UNO in order to read data.

Best reggards.

**Comment by jrbenito** [comment]
Hi @SardinasJL 

Sorry for late reply, I am busy on my day job and little of from GitHub this days.

I updated the README in this repository couple of days ago. This library was never finished because I ended up selling my house and setup, moved to another country where I have no access to this protocol to test.

What I do have and might help you is this code: https://github.com/jrbenito/PIMA-node

it run for a year or so without any issues in a similar (compatible) Arduino Uno board. Hence, few modifications shall be necessary to make it work for you. Please, **keep in mind**  that, although this code run for a very long time without presenting issues for my setup, _it is far from being well written and tested_.

And, as always: AC energy can kill, please, be careful and know what you are doing.

Abraço
